LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:=mysyscall.c
LOCAL_MODULE:=ptree
LOCAL_CFLAGS+=-pie -fPIE
LOCAL_LDFLAGS+=-pie -fPIE
LOCA_FORCE_STATIC_EXECUTABLE:=true

include $(BUILD_EXECUTABLE)

